name: Build & Push to Amazon ECR Public

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  PUBLIC_ECR_REPO: "public.ecr.aws/y5h2u1j4/github_action_nginx"
  IMAGE_TAG: "latest" # or use ${{ github.run_number }} for unique tags

jobs:
  build:
    runs-on: [ self-hosted, dev]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region "${AWS_REGION}" \
          | docker login --username AWS --password-stdin public.ecr.aws/y5h2u1j4

      - name: Build Docker Image
        run: |
          docker build -t github_action_nginx .

      - name: Tag Docker Image
        run: |
          docker tag github_action_nginx:latest "${PUBLIC_ECR_REPO}:${IMAGE_TAG}"

      - name: Push Image to ECR Public
        run: |
          docker push "${PUBLIC_ECR_REPO}:${IMAGE_TAG}"

      - name: Stop old container and run new one
        run: |
          docker ps -aq -f name=sairam | xargs -r docker stop
          docker ps -aq -f name=sairam | xargs -r docker rm
          docker run -d --name sairam "${PUBLIC_ECR_REPO}:${IMAGE_TAG}"
